# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "PLACEHOLDER"
name = "stickyclick"
application_url = "https://stickyclick.example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [webhooks.privacy_compliance]
  customer_data_request_url = "/webhooks/customers/data_request"
  customer_deletion_url = "/webhooks/customers/redact"
  shop_deletion_url = "/webhooks/shop/redact"

[access_scopes]
scopes = ""

[auth]
redirect_urls = [ "https://stickyclick.example.com/auth/callback" ]
